#represents the name of the project.
name: mobile_assignment_3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish the package

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

#represents the dependencies required for the project.
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  intl: ^0.18.0
  cupertino_icons: ^1.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
